<?xml version="1.0" encoding="UTF-8"?>
<project name="SistemaBancarioNetBeans" default="run" basedir=".">
    <description>Projeto simples de sistema bancário para Apache NetBeans.</description>

    <property file="nbproject/project.properties"/>

    <target name="clean">
        <delete dir="${build.dir}"/>
        <delete dir="${dist.dir}"/>
    </target>

    <target name="compile">
        <mkdir dir="${build.classes.dir}"/>
        <javac srcdir="${src.dir}"
               destdir="${build.classes.dir}"
               includeantruntime="false"
               encoding="UTF-8"
               source="${javac.source}"
               target="${javac.target}"/>
    </target>

    <target name="jar" depends="compile">
        <mkdir dir="${dist.dir}"/>
        <jar destfile="${dist.jar}" basedir="${build.classes.dir}">
            <manifest>
                <attribute name="Main-Class" value="${main.class}"/>
            </manifest>
        </jar>
    </target>

    <target name="run" depends="compile">
        <java classname="${main.class}" fork="true">
            <classpath>
                <pathelement path="${build.classes.dir}"/>
            </classpath>
        </java>
    </target>
</project>
