<?xml version="1.0" encoding="UTF-8"?>
<project name="ProjetoAnimais" default="run" basedir=".">
    <property file="nbproject/project.properties"/>

    <target name="clean">
        <delete dir="${build.dir}"/>
        <delete dir="${dist.dir}"/>
    </target>

    <target name="compile">
        <mkdir dir="${build.classes.dir}"/>
        <javac srcdir="${src.dir}" destdir="${build.classes.dir}"
               includeantruntime="false" encoding="UTF-8"
               source="${javac.source}" target="${javac.target}"/>
    </target>

    <target name="run" depends="compile">
        <java classname="${main.class}" fork="true">
            <classpath>
                <pathelement path="${build.classes.dir}"/>
            </classpath>
        </java>
    </target>
</project>
